[theme]
primaryColor = "#DE1B1B"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F5F5F5"
textColor = "#000000"
font = "sans serif"

[server]
headless = true
port = 8501

[browser]
gatherUsageStats = false
